name: "RyanJarv's Blog"
description: "Mostly about AWS, Infrastructure, and Security"
url: "https://blog.ryanjarv.sh/"
author:
  twitter: ryan_jarv
defaults:
  - scope:
      path: "resumes"
    values:
      pdf: true
#plugins:
#  - jekyll-feed
include: [".well-known", "resources/js"]
